### Exercises
 
1. Rerun the last regression where, only including oecd countries in the subset. A list of OECD countries is provided. You will need to find the 3 letter ISO code associated with each country. (Hint: Reimport the dataframe we saved early in the lesson)

2. Plot the residuals in a histogram. Explain why the shape of the distribution of these residuals are distinct from the shape of the residuals plotted in the first regressions from this lesson.

3. Plot seperate scatter plots for each variable (x-axis) against the predictor (y-axis). ThenPlot seperate scatter plots for each variable (x-axis) against the predictor (y-axis). Do we observe bias in the resdiuals when controlling for each variable? Why does this matter?

4. Plot the observed and predicted values of RGDP Per Capita for each individual country.

5. Repeat questions 1 through 4 using 2 year lags and differences instead of 5 year lags and differences.

In [164]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import datetime as dt
import matplotlib.pyplot as plt

In [165]:
oecd_countries = ["Australia", "Austria", "Belgium", "Canada", "Chile", "Colombia", "Costa Rica",
            "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany",
            "Greece", "Hungary", "Iceland", "Ireland", "Israel", "Italy", "Japan", 
            "Latvia", "Lithuania","Luxembourg", "Mexico", "Netherlands", "New Zealand", "Norway",
             "Poland","Portugal", "Slovakia", "Slovenia", "South Korea", "Spain", "Sweden",
             "Switzerland", "Turkey", "United Kingdom", "United States"]

In [166]:
hw_data = pd.read_excel("EFWAndRGDP.xls")
data = hw_data[hw_data["Countries"].isin(oecd_countries)].dropna(how = "all", axis = 1)

### Use statsmodels.api to reconstruct and compare stats

In [167]:
data.reset_index(inplace=True)
data["Year"] = data["Year"].astype(str).astype("datetime64[ns]").sort_index()
data = data.set_index(["Countries", "Year"]).sort_index()
data

                          index ISO_Code_3 ISO_Code_2    World Bank Region  \
Countries     Year
Australia     1970-01-01    245        AUS         AU  East Asia & Pacific
              1975-01-01    250        NaN         AU  East Asia & Pacific
              1980-01-01    255        NaN         AU  East Asia & Pacific
              1985-01-01    260        NaN         AU  East Asia & Pacific
              1990-01-01    265        NaN         AU  East Asia & Pacific
...                         ...        ...        ...                  ...
United States 2014-01-01   7786        NaN         US        North America
              2015-01-01   7787        NaN         US        North America
              2016-01-01   7788        NaN         US        North America
              2017-01-01   7789        NaN         US        North America
              2018-01-01   7790        NaN         US        North America

                         World Bank Current Income Classification, 1990-present (L=Low income, LM=Lower middle income, UM=Upper middle income, H=High income)  \
Countries     Year
Australia     1970-01-01                                                NaN
              1975-01-01                                                NaN
              1980-01-01                                                NaN
              1985-01-01                                                NaN
              1990-01-01                                                  H
...                                                                     ...
United States 2014-01-01                                                  H
              2015-01-01                                                  H
              2016-01-01                                                  H
              2017-01-01                                                  H
              2018-01-01                                                  H

                           Summary  Size of Government  \
Countries     Year
Australia     1970-01-01  7.291154            6.863768
              1975-01-01  7.002204            6.255684
              1980-01-01  7.316469            6.339449
              1985-01-01  7.670016            6.259326
              1990-01-01  7.927001            6.708215
...                            ...                 ...
United States 2014-01-01  8.249649            7.239681
              2015-01-01  8.309574            7.237673
              2016-01-01  8.339536            7.252009
              2017-01-01  8.379486            7.354358
              2018-01-01  8.279612            7.409095

                          Legal System and Property Rights  Sound Money  \
Countries     Year
Australia     1970-01-01                          7.775615     9.581113
              1975-01-01                          8.034445     8.346907
              1980-01-01                          8.037057     9.085686
              1985-01-01                          8.540345     9.089736
              1990-01-01                          8.398730     9.018318
...                                                    ...          ...
United States 2014-01-01                          7.652463     9.737154
              2015-01-01                          7.745733     9.855788
              2016-01-01                          7.793107     9.814703
              2017-01-01                          7.802657     9.772320
              2018-01-01                          7.646530     9.772494

                          Freedom to Trade Internationally  Regulation  \
Countries     Year
Australia     1970-01-01                          5.882101    6.335298
              1975-01-01                          5.692162    6.761980
              1980-01-01                          5.841104    7.389934
              1985-01-01                          6.985368    7.469774
              1990-01-01                          7.661409    7.750886
...                                                    ...         ...
United States 2014-01-01                          7.836022    8.792114
              2015-01-01                          7.810632    8.891698
              2016-01-01                          7.889129    8.952382
              2017-01-01                          7.921225    9.031901
              2018-01-01                          7.783384    8.784245

                          RGDP Per Capita
Countries     Year
Australia     1970-01-01       19166.0000
              1975-01-01       20993.0000
              1980-01-01       22972.0000
              1985-01-01       24927.0000
              1990-01-01       27373.0000
...                                   ...
United States 2014-01-01       51664.0000
              2015-01-01       52591.0000
              2016-01-01       53015.0000
              2017-01-01       54007.7698
              2018-01-01       55334.7394

[900 rows x 12 columns]

In [168]:
data.keys()

Index(['index', 'ISO_Code_3', 'ISO_Code_2', 'World Bank Region',
       'World Bank Current Income Classification, 1990-present (L=Low income, LM=Lower middle income, UM=Upper middle income, H=High income)',
       'Summary', 'Size of Government', 'Legal System and Property Rights',
       'Sound Money', 'Freedom to Trade Internationally', 'Regulation',
       'RGDP Per Capita'],
      dtype='object')

In [169]:
# Remove any columns not used
data = data[data.keys()[5:]]
data.sort_index(inplace = True)
data

C:\Users\calvi\AppData\Local\Temp\ipykernel_3068\3501341935.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.sort_index(inplace = True)

                           Summary  Size of Government  \
Countries     Year
Australia     1970-01-01  7.291154            6.863768
              1975-01-01  7.002204            6.255684
              1980-01-01  7.316469            6.339449
              1985-01-01  7.670016            6.259326
              1990-01-01  7.927001            6.708215
...                            ...                 ...
United States 2014-01-01  8.249649            7.239681
              2015-01-01  8.309574            7.237673
              2016-01-01  8.339536            7.252009
              2017-01-01  8.379486            7.354358
              2018-01-01  8.279612            7.409095

                          Legal System and Property Rights  Sound Money  \
Countries     Year
Australia     1970-01-01                          7.775615     9.581113
              1975-01-01                          8.034445     8.346907
              1980-01-01                          8.037057     9.085686
              1985-01-01                          8.540345     9.089736
              1990-01-01                          8.398730     9.018318
...                                                    ...          ...
United States 2014-01-01                          7.652463     9.737154
              2015-01-01                          7.745733     9.855788
              2016-01-01                          7.793107     9.814703
              2017-01-01                          7.802657     9.772320
              2018-01-01                          7.646530     9.772494

                          Freedom to Trade Internationally  Regulation  \
Countries     Year
Australia     1970-01-01                          5.882101    6.335298
              1975-01-01                          5.692162    6.761980
              1980-01-01                          5.841104    7.389934
              1985-01-01                          6.985368    7.469774
              1990-01-01                          7.661409    7.750886
...                                                    ...         ...
United States 2014-01-01                          7.836022    8.792114
              2015-01-01                          7.810632    8.891698
              2016-01-01                          7.889129    8.952382
              2017-01-01                          7.921225    9.031901
              2018-01-01                          7.783384    8.784245

                          RGDP Per Capita
Countries     Year
Australia     1970-01-01       19166.0000
              1975-01-01       20993.0000
              1980-01-01       22972.0000
              1985-01-01       24927.0000
              1990-01-01       27373.0000
...                                   ...
United States 2014-01-01       51664.0000
              2015-01-01       52591.0000
              2016-01-01       53015.0000
              2017-01-01       54007.7698
              2018-01-01       55334.7394

[900 rows x 7 columns]

In [170]:
reg_vars = list(data.keys())
reg_vars

['Summary',
 'Size of Government',
 'Legal System and Property Rights',
 'Sound Money',
 'Freedom to Trade Internationally',
 'Regulation',
 'RGDP Per Capita']

In [171]:
y_var = [reg_vars[-1]] 
x_vars = reg_vars[1:-1]
y_var, x_vars

(['RGDP Per Capita'],
 ['Size of Government',
  'Legal System and Property Rights',
  'Sound Money',
  'Freedom to Trade Internationally',
  'Regulation'])

In [182]:
reg_data = data[reg_vars].dropna() # Dropna to make sure that the sm library works

In [179]:
reg_data

                           Summary  Size of Government  \
Countries     Year
Australia     1970-01-01  7.291154            6.863768
              1975-01-01  7.002204            6.255684
              1980-01-01  7.316469            6.339449
              1985-01-01  7.670016            6.259326
              1990-01-01  7.927001            6.708215
...                            ...                 ...
United States 2014-01-01  8.249649            7.239681
              2015-01-01  8.309574            7.237673
              2016-01-01  8.339536            7.252009
              2017-01-01  8.379486            7.354358
              2018-01-01  8.279612            7.409095

                          Legal System and Property Rights  Sound Money  \
Countries     Year
Australia     1970-01-01                          7.775615     9.581113
              1975-01-01                          8.034445     8.346907
              1980-01-01                          8.037057     9.085686
              1985-01-01                          8.540345     9.089736
              1990-01-01                          8.398730     9.018318
...                                                    ...          ...
United States 2014-01-01                          7.652463     9.737154
              2015-01-01                          7.745733     9.855788
              2016-01-01                          7.793107     9.814703
              2017-01-01                          7.802657     9.772320
              2018-01-01                          7.646530     9.772494

                          Freedom to Trade Internationally  Regulation  \
Countries     Year
Australia     1970-01-01                          5.882101    6.335298
              1975-01-01                          5.692162    6.761980
              1980-01-01                          5.841104    7.389934
              1985-01-01                          6.985368    7.469774
              1990-01-01                          7.661409    7.750886
...                                                    ...         ...
United States 2014-01-01                          7.836022    8.792114
              2015-01-01                          7.810632    8.891698
              2016-01-01                          7.889129    8.952382
              2017-01-01                          7.921225    9.031901
              2018-01-01                          7.783384    8.784245

                          RGDP Per Capita
Countries     Year
Australia     1970-01-01       19166.0000
              1975-01-01       20993.0000
              1980-01-01       22972.0000
              1985-01-01       24927.0000
              1990-01-01       27373.0000
...                                   ...
United States 2014-01-01       51664.0000
              2015-01-01       52591.0000
              2016-01-01       53015.0000
              2017-01-01       54007.7698
              2018-01-01       55334.7394

[869 rows x 7 columns]

In [180]:
y = reg_data[y_var]
X = reg_data[x_vars]
X["Constant"] = 1
X
results = sm.OLS(y,X).fit()
results

C:\Users\calvi\AppData\Local\Temp\ipykernel_3068\3495529059.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Constant"] = 1

In [181]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:        RGDP Per Capita   R-squared:                       0.565
Model:                            OLS   Adj. R-squared:                  0.562
Method:                 Least Squares   F-statistic:                     224.0
Date:                Sun, 23 Apr 2023   Prob (F-statistic):          3.60e-153
Time:                        23:32:01   Log-Likelihood:                -9174.3
No. Observations:                 869   AIC:                         1.836e+04
Df Residuals:                     863   BIC:                         1.839e+04
Df Model:                           5
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Size of Government                -820.3802    350.222     -2.342      0.019   -1507.767    -132.994
Legal System and Property Rights  6102.0250    367.185     16.618      0.000    5381.345    6822.705
Sound Money                       2250.7536    312.911      7.193      0.000    1636.598    2864.909
Freedom to Trade Internationally  -792.1670    371.394     -2.133      0.033   -1521.109     -63.225
Regulation                        2298.3939    467.796      4.913      0.000    1380.243    3216.545
Constant                         -3.934e+04   3385.581    -11.619      0.000    -4.6e+04   -3.27e+04
==============================================================================
Omnibus:                      205.420   Durbin-Watson:                   0.200
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              585.081
Skew:                           1.178   Prob(JB):                    8.94e-128
Kurtosis:                       6.257   Cond. No.                         182.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
predictor = results.predict()
reg_data[y_var[0] + " Predictor"] = predictor
reg_data

In [ ]:
y_hat = reg_data[y_var[0] + " Predictor"]
y_mean = reg_data[y_var[0]].mean()
y = reg_data[y_var[0]]


reg_data["Residuals"] = (y.sub(y_hat))
reg_data["Squared Explained"] = y_hat.sub(y_mean).pow(2)
reg_data["Squared Residuals"] = y.sub(y_hat).pow(2)
reg_data["Squared Totals"] = y.sub(y_mean).pow(2)
reg_data

In [ ]:
SSR = reg_data["Squared Explained"].sum()
SSE = reg_data["Squared Residuals"].sum()
SST = reg_data["Squared Totals"].sum()
SSR,SSE,SST

In [ ]:
n = results.nobs
k = len(results.params)
estimator_variance = SSE / (n - k)
n, k, estimator_variance

In [ ]:
cov_matrix = results.cov_params()
cov_matrix

In [ ]:
# Calculate covariance matrix by hand
XtXInv = np.matrix(np.matmul(X.T,X)).getI()

# multiply by the estimator variance
evmult = estimator_variance * XtXInv

# transform to pd dataframe
pd.DataFrame(evmult, columns = X.keys(), index = X.keys())

In [ ]:
results.params

In [ ]:
parameters = {}
for x_var in x_vars:
    parameters[x_var] = {}
    parameters[x_var]["Beta"] = results.params[x_var]
    parameters[x_var]["Standard Error"] = cov_matrix.loc[x_var, x_var] ** (1/2)
    parameters[x_var]["t-stats"] = parameters[x_var]["Beta"] / parameters[x_var]["Standard Error"] 
parameters = pd.DataFrame(parameters).T
parameters

In [ ]:
r2 = SSR/SST
r2_adjusted = 1 - (SSE / (n - k)) / (SST / (n - 1))
r2_adjusted, r2

In [ ]:
plt.rcParams.update({"font.size":26})
fig, ax = plt.subplots(figsize = (12,8))
reg_data[["Residuals"]].plot.hist(bins = 100, ax = ax)
plt.xticks(rotation=60)

In [ ]:
fig, ax = plt.subplots(figsize = (12,8))
reg_data[["Squared Residuals"]].plot.hist(bins =100, ax = ax)

In [ ]:
np.log(data[y_var]).diff(5).plot.hist(bins=10)

# Lag

In [ ]:
# Regressions with Logged differences
years_diff = 5
reg_data = data
reg_data["RGDP Per Capita"] = np.log(data["RGDP Per Capita"]).groupby("ISO_Code_3").diff(years_diff).=

# Take the log of real gdp then difference within group
reg_data = reg_data.replace([np.inf, -np.inf], np.nan)

In [ ]:
y = r_df[y_var]
X = r_df[x_vars]
X,y

In [ ]:
r_df = reg_data.dropna(axis = 0, how = "any")
y = r_df[y_var]
X = r_df[x_vars]
X["Constant"] = 1
results = sm.OLS(y, X).fit()
r_df["Predictor"] = results.predict()
r_df["Residuals"] = results.resid
results.summary()

In [ ]:
r_df["Residuals"] = results.resid
fig, ax = plt.subplots(figsize = (12,8))

ax.axvline(r_df["Residuals"].mean(), ls = "--", linewidth = 5, color = 'k')
r_df[["Residuals"]].plot.hist(bins = 100, ax = ax)

In [ ]:
resultsDict = {"Beta Estimates" : results.params,
              "t-stats":results.tvalues,
              "p-values":results.pvalues,
              "Standard Errors":results.bse}
resultsDF = pd.DataFrame(resultsDict).round(3)
resultsDF.to_csv("y = RGDPC, X = EFW, LogDiffResults.csv")
resultsDF

In [ ]:
fig, ax = plt.subplots(figsize = (20,10))
r_df.plot.scatter(x = y_var[0],
                 y = "Predictor", 
                  s = 50, 
                  alpha = .7,
                  ax = ax)

In [ ]:
all_vars = y_var + x_vars
for var in all_vars:
    fig,ax=plt.subplots(figsize=(20,12))
    r_df.plot.scatter(x=var,y="Residuals",s=50,alpha=.5,ax=ax)

    ax.axhline(r_df["Residuals"].mean(), ls = "--", linewidth = 5, color = 'k')

In [ ]:
cumulative_data = r_df[[y_var[0], "Predictor"]] + 1
cumulative_data